import Head from 'next/head'
import Sidebar from '@/components/Sidebar'

export default function Home() {
  return (
    <>
      <Head>
        <title>WebChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="referrer" content="no-referrer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  )
}
